# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Economics 299 - Python for Economics
email: pwalton@brandeis.edu
description: > # this means to ignore newlines until "baseurl:"
  We have developed this site to showcase our code and acheivements from a semester learning python and applying our newly enhanced data analysis skills to economic data.
baseurl: "" # the subpath of your site, e.g. /blog
url: "econ299.github.io" # the base hostname & protocol for your site
twitter_username: forecasterenten
github_username:  econ299

# Build settings
markdown: kramdown
