# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Econ 299, Python for economics
email: pwalton@brandeis.edu
description: > # this means to ignore newlines until "baseurl:"
    We have been working on learning Python for Economics in an Independent Study through Brandeis University's 
    International Business School. We made this website together to show you what we've done!
    
    Special thanks to Professor George Hall for guiding us through and being our advisor for this class
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://econ299.github.io" # the base hostname & protocol for your site
twitter_username: M0NEYP3NNY
github_username:  econ299

# Build settings
markdown: kramdown
